[env]
TERM = "xterm-256color"

[font]
normal = { family = "FiraCode Nerd Font", style = "Retina" }
size = 18

[window]
startup_mode = "Maximized"

[general]
import = ["~/.config/alacritty/catppuccin-latte.toml"]
